schema_version = "1.0.0"
id = "blender_json_mcp"
version = "1.0.0"
name = "Blender JSON MCP"
tagline = "JSON APIサーバー (FastAPI/GraphQL)"
maintainer = "User <user@example.com>"
type = "add-on"

website = "https://github.com/mintiasaikoh/Blender_json_MCP"

tags = ["Development", "API", "Network"]

blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025 User",
]

[permissions]
network = "JSON APIサーバーの実行とネットワーク通信"
files = "ログファイルの保存と読み込み"
