[extension]
id = "blender_graphql_mcp"
version = "1.2.0"
name = "Blender GraphQL MCP"
tagline = "AI-powered Blender control through Model Context Protocol"
maintainer = "Blender GraphQL MCP Team"
license = "GPL-3.0-or-later"
blender_version_min = "4.2.0"

[requirements]
pip = [
    "fastapi~=0.109.0",
    "uvicorn~=0.25.0",
    "strawberry-graphql~=0.232.2",
    "pydantic>=2.4.0",
    "aiofiles~=23.2.1",
    "websockets~=12.0",
    "numpy>=1.21.0",
    "pandas>=1.3.0"
]